let msg = "   Hello    ";
console.log("WHen written without trimming",msg);
console.log("When written after trimming the msg string",msg.trim());
let name  = "     Gaurav   singh     ";
console.log("The name without trimming the name string",name);
console.log("The name after trimming the name string",name.trim());
console.log("From the above we can aclearly view that the string before and after whitespace is removed when we use trim function but in betweeen whitespace is not trimmed..");
let string = "RandomString";
upperCase = string.toUpperCase();
console.log("Before capitalise the actual string will be:",string);
console.log("After capitalise the new upper case will be:",upperCase);
let string1 = "Myself";
console.log("The string1 without the lowercase operation",string1);
console.log("The string1 after doing the lowercase operation",string1.toLowerCase());
console.log("strings methods with arguments....");
let str = "I love coding";
console.log("The index of the word love in the string 'I love coding' is ",str.indexOf("love"));
console.log(str.indexOf("j"));
let username = " Gaurav singh ";
console.log("The string without doing the chaining operation",username);
newusername = username.trim().toUpperCase();
console.log("The string after doing the chaining operation",newusername);
let sentence = " I love coding";
console.log(sentence.slice(5)); // from index 5 to last all index element will be returned...
console.log(sentence.slice(1,5));
console.log(sentence.slice(-1)); // this means length - num
console.log(sentence.replace("love","do"));
console.log(sentence.replace("o","X"));
let fruit = "mango ";
console.log(fruit.repeat(3));
let message = " Help! "
console.log(message.trim().toUpperCase());
let array = ["aman" , "Priya" , "ramdev"];
console.log(array);
console.log(array.length);
let marks = [99,69,76,56];
console.log(marks);
let names = ["adam" , "bob" , "catlyn"];
console.log(names);
let info = ["aman",  25 , 6];
console.log(info);
console.log(info[0]);
let vegetables = ["potato", "tomato" , "onion"];
console.log(vegetables);
vegetables[10] = "guava";
console.log(vegetables);
cars = ["audi" , "ferrari" , "bmw" , "mercedes"];
cars.push("toyota");
console.log(cars); 
cars.push("mahindra");
console.log(cars);
cars.pop();
console.log(cars);
primary = ["red" , "yellow" , "green" , "black", "white"];
console.log("The index of the green is ",primary.indexOf("green"));
console.log("The index of the green is ",primary.indexOf("white"));
console.log(primary.includes("red"));
console.log(primary.includes("violent"));
let secondary = ["tom" , "jeery" , "bheem" , "kitten"];
console.log(primary.concat(secondary));
console.log(primary.slice(2));
console.log(primary.slice(2,3));
console.log(primary.slice(-2));
console.log(primary.reverse());
console.log(primary.splice (0,2,"purple","royal blue"));
let days = ["monday" , "tuesday" , "wednesday" , "thursday" , "friday"  , "saturday"];
console.log(days.sort());
let arr = ['a' , 'b'];
let arrcopy = arr;
console.log(arrcopy);
console.log(arrcopy.push('c'));
console.log(arr);
console.log(arr == arrcopy);
let num = [[1,2],[3,4],[5,6]];
console.log(num);